add wave -noupdate /b12_testbench/stimuli/clk
add wave -noupdate /b12_testbench/stimuli/reset
add wave -noupdate /b12_testbench/stimuli/q
add wave -noupdate /b12_testbench/dut/clock
add wave -noupdate /b12_testbench/dut/start
add wave -noupdate /b12_testbench/dut/reset
add wave -noupdate /b12_testbench/dut/k
add wave -noupdate /b12_testbench/dut/nloss
add wave -noupdate /b12_testbench/dut/nl
add wave -noupdate /b12_testbench/dut/speaker
